export const SET_AUTH_USER = "SET_AUTH_USER";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const CHANGE_ROLE = "CHANGE_ROLE";

export const SET_FORM_REQUEST = "SET_FORM_REQUEST";
export const SET_REGIESTER_COURSE = "SET_REGIESTER_COURSE";
export const CLEAR_REGISETR_COURSE = "CLEAR_REGISETR_COURSE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_COURSE = "ADD_COURSE";
export const ADD_MODULE = "ADD_MODULE";
export const ADD_TEACHER_COURSE = "ADD_TEACHER_COURSE";
export const ADD_TEACHER_MODULE = "ADD_TEACHER_MODULE";
export const ADD_TEACHER_CURRENT_COURSE = "ADD_TEACHER_CURRENT_COURSE";
export const ADD_STUDENT_CURRENT_COURSE = "ADD_STUDENT_CURRENT_COURSE";
export const ADD_PAYMENT = "ADD_PAYMENT";
export const ADD_ADMIN_COURSE = "ADD_ADMIN_COURSE";
