import React from "react";
import { Modal, Button, Row, Col, Form } from "react-bootstrap";
import styles from "./t&cStyle.module.css";
// import enhancer from "./enhancer";
import _ from "lodash";

const Index = (props) => {
  let { auth, deleteParicularBatches, loader } = props;

  return (
    <React.Fragment>
      <Modal
        {...props}
        id="testModalforRadius"
        size="xl"
        aria-labelledby="contained-modal-title-vcenter"
        centered
        style={{ borderRadius: "25px" }}
      >
        <Modal.Header style={{ border: "none" }} closeButton>
          <span
            style={{ color: "#3d736d", textAlign: "center", marginLeft: "40%" }}
          >
            {" "}
            Terms of Use for Eumetry
          </span>
        </Modal.Header>

        <Modal.Body style={{ padding: "15px" }}>
          <div
            // className={styles.deleteBatchtHeaderDiv}
            style={{ marginBottom: "5%", padding: "10px" }}
          >
            {/* <span style={{ color: "#3d736d" }}> Terms of Use for Eumetry</span>
                        <p id={styles.deleteBatchtContent}>
                            Terms of Use for Eumetry
            </p> */}

            <p>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and the Information Technology
              (Intermediaries guidelines) Rules, 2011 thereunder, as amended
              from time to time, as applicable and the amended provisions
              pertaining to electronic records in various statutes as amended by
              the Information Technology Act, 2000. This electronic record is
              generated by a computer system and does not require any physical
              or digital signature.
            </p>

            <p>
              The site [.] (hereinafter referred to as "Website") is owned by
              Zotalabs Private Limited (hereinafter referred to as
              "ZOTALABS/Company").
            </p>

            <p>
              That Eumetry is an e-learning and teaching space that provides a
              platform to create content to teachers and conduct courses. It
              gives an open access to publish and market content and does not
              hold any right or copyright of the content uploaded. That the sole
              ownership of the content and its authenticity is on the content
              creator and not of Eumetry.
            </p>

            <p>
              Your use of the Website, applications, services and products are
              governed by the following terms and conditions ("Terms of
              Use/Agreement") as applicable including the applicable policies
              which are incorporated herein by way of reference. If you transact
              on the Website, you shall be subject to the policies that are
              applicable to the Website for such transaction. By mere use of the
              Website, you shall be contracting with ZOTALABS and these terms
              and conditions including the policies constitute your binding
              obligations, with ZOTALABS.
            </p>

            <p>
              Please read the Terms of Use and the privacy policy of the Company
              (<span style={{ fontWeight: "bold" }}>“Privacy Policy”</span>)
              with respect to registration with us, the use of the Website,
              applications, services and products carefully before using the
              Website, applications, services or products.
            </p>

            <br />
            <br />
            <br />
            <p>
              In event wherein there arises a discrepancy between the Terms of
              Use and other policies of any product of Eumetry, the provisions
              of these Terms of Use shall prevail.
            </p>
            <div style={{ marginLeft: "25px", marginRight: "25px" }}>
              <p>
                For availing the services under the Website, registration by the
                user is required. When you sign into your Eumetry account
                (assuming there is a login system) you share with us your name,
                password, your payment method(if any) and other personal
                details.. We also collect the content you create, upload when
                using these services. It further includes the photos and videos
                you save and document you create or receive while being logged
                into this application.You will receive a password and account
                designation upon completing the registration on the Website. You
                are responsible for maintaining the confidentiality of the
                password and account and are fully responsible for all
                activities that occur under your password or account. By
                registering, you agree to the following terms in addition to any
                other specific terms which shall be posted at an appropriate
                location of the Website. Each registration is for a single
                individual user only. To access these services, you will be
                asked to enter your individual User Name and Password.
                Therefore, we do not permit any of the following:-
              </p>

              {/* here need to add dots starts */}
              <p>
                {/* <span id={styles.dot}></span>helooo */}
                {/* <span styles={{height:"5px",width:"5px",backg}}></span>helooo */}
                ⦁ Any other person sharing your User Name and Password;
              </p>
              <p>
                {" "}
                ⦁ Any part of the Website being cached in proxy servers and
                accessed by individuals who have not registered with the Website
                as users;
              </p>

              <p>
                {" "}
                ⦁ Access through a single User Name and Password being made
                available to multiple users on a network.
              </p>
              {/* here need to add dots ends */}

              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                2. COPYRIGHT OWNERSHIP
              </p>
              <br />
              <br />
              <p>
                By uploading Content on Eumetry platform, you undertake and that
                you are the legal and absolute owner of the Content , or have
                been awarded full and unrestricted rights from the copyright
                owner to upload and utilise the Content for commercial use of
                the Eumetry Guides or any other distribution channels including,
                but not limited to the Eumetry, selected 3rd party websites and
                Eumetry (Guides.){" "}
              </p>

              <br />
              <br />
              <p>
                You understand and acknowledge that Content which is not your
                brain product or does not have written agreement of the
                copywriter for commercial usage will be deleted due to
                infringement of the copyright laws in accordance with section 63
                of Copyright Act,1957. Any content which falls under the heads
                of “obscene”or “ponography” will attract monetary and punitive
                actions in accordance with section 67 of Information technology
                act 2000.
              </p>
              <br />
              <br />

              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                3. THIRD PARTY RIGHTS
              </p>
              <p>
                By uploading Content and using our platform, you undertake that:
              </p>
              <br />
              <br />
              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dot */}
                ⦁ The content uploaded does not violate the rights of any party,
                does not result in a breach of contract between you and another
                party
                <br />
                {/* dot */}
                ⦁ Any legal encumbrances or liabilities arising from such
                content is your liability.
                <br />
                {/* dot */}
                you accept responsibility for any royalties or fees due to any
                party from the use of such content.
              </p>

              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                4. Individual projected in the Content-
              </p>
              <br />
              <p>By uploading the Content you undertake and guarantee that</p>
              <br />
              <p>
                Any individual clearly identifiable has given their absolute and
                irreversible consent to be used, printed or displayed, and
                accept full responsibility for any such use.
              </p>
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                5. Accepting and rejecting Content
              </p>
              <br />
              <p>You acknowledge and understand that :</p>
              <br />
              <br />
              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dots */}
                ⦁ All the content uploaded on Eumetry will be assessed, filtered
                by Eumetry Editor for suitability.The Editor reserves the
                absolute right to reject or accept the content for uploading
                <br />
                {/* dot */}
                ⦁ Content so rejected during the quality check will be deleted
                from Eumetry entirely, with no copies remaining in the Eumetry
                system.
                <br />
                {/* dot */}
                ⦁ The decisions of the Editor are irrevocable.
                <br />
                {/* dot */}⦁ Eumetry reserves the right to reject and remove any
                uploaded Content from display on its website, for any reason, at
                any time, without prior notice.
              </p>

              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                6. RESPONSIBILITY FOR CONTENT
              </p>
              <br />

              <p>While using the platform, you undertake that:</p>

              <br />
              <br />
              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dot */}
                ⦁ you are solely responsible for the content uploaded by you and
                for any offence, objections, encumbrances, claims or damages
                that arise from the content of that Image.
                <br />
                {/* dot */}
                ⦁ The approval of Images in the Guides by Eumetry in no way
                alters or diminishes your responsibility towards content shared
                by you.
                <br />
                {/* dot */}
                ⦁ Nor does it transfer any responsibility for the content of the
                Image to Eumetry or the Editor.
                <br />
                {/* dot */}
                <span style={{ textDecoration: "underline" }}>
                  ⦁ You should not send, submit, post, or otherwise transmit,
                  material or messages that contain software virus, or any other
                  files that are designed to interrupt, destroy, and negatively
                  affect in any manner whatsoever, any electronic equipment in
                  connection with the use of the Website, or other user's
                  ability to use the Website.
                </span>
              </p>

              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                7. RIGHTS GRANTED TO Eumetry:
              </p>
              <br />
              <p>
                ZOTALABS is the owner of the Website. However, the ownership of
                the Content is with the creator of that specific Content. The
                Company does not have any ownership rights on the Content
                available on the Website. We are the licensee of all copyrights,
                trademarks, service marks or any other intellectual property in
                the Content published on the Website. All such rights are
                reserved. You must not modify the paper or digital copies of any
                materials you have printed off or downloaded in any way, and you
                must not use any illustrations, photographs, video or audio
                sequences or any graphics separately from any accompanying text.
                You must not use any part of the Content on the Website for
                commercial purposes without obtaining a licence to do so from us
                or our licensors.
              </p>
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                8. NO DERIVATIVE WORKS OF USER IMAGES:
              </p>
              <br />
              <p>
                Eumetry guarantees that it will not create any derivative work
                from the Content developed and uploaded by you nor will modify
                the content without your consent, though it reserves the right
                to crop images or videos or to make cosmetic changes like
                adjustments to the brightness, exposure,colours or general
                appearance of any Image that it believes warrants such
                adjustment for the purpose of better display.
              </p>

              <br />
              <b />

              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                9. SELECTED IMAGES FOR PROMOTIONS
              </p>
              <br />
              <p>
                Eumetry may select certain aspects of your content (like Images)
                that you upload on Eumetry for promotional activities of Eumetry
                business, including but not limited to: use in Eumetry’ own
                promotional materials either on-line or in printed form.
              </p>
              <br />
              <br />

              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                10. IMAGE CONTENT
              </p>
              <br />
              <br />
              <p>
                While uploading the content, following points need to be
                considered:
              </p>
              <br />
              <br />
              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dot */}

                <span>
                  {" "}
                  ⦁ You should only upload Images that are relevant and
                  appropriate to your campsite. Images including overlays such
                  as logos, text or star ratings will not be approved as these
                  do not render well.
                </span>
                <br />
                {/* dot */}
                <span>
                  {" "}
                  ⦁ You must not upload photographs that contain objectionable
                  content, including but not limited to nudity, violence, and
                  other offensive, illegal or inappropriate images or videos.
                  Any content that falls under the category of obscene will
                  attract punitive actions covered under Information Technology
                  Act, 2000 , Indian Penal Code.
                </span>
                <br />
                {/* dot */}
                <span>
                  ⦁ The content of some Images - particularly nudity is
                  considered offensive Thus Eumetry reserves the right to delete
                  Images, videos, audios that fall in the category of “
                  sensitive”.
                </span>
              </p>
              <br />
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                11. Links To Other Web Sites
              </p>
              <br />
              <br />
              <p>
                Our Service may contain links to third party web sites or
                services that are not owned or controlled by the Company. The
                Company has no control over, and assumes no responsibility for
                the content, privacy policies, or practices of any third party
                web sites or services. We do not warrant the offerings of any of
                these entities/individuals or their websites.
              </p>
              <br />
              <br />
              <p>
                You acknowledge and agree that ZOTALABS shall not be responsible
                or liable, directly or indirectly, for any damage or loss caused
                or alleged to be caused by or in connection with use of or
                reliance on any such content, goods or services available on or
                through any such third party web sites or services. We strongly
                advise you to read the terms and conditions and privacy policies
                of any third party web sites or services that you visit.
              </p>

              <br />
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                INDEMNITY FROM CLAIMS
              </p>

              <br />
              <br />
              <p>
                You agree to defend, indemnify and hold harmless ZOTALABS and
                its subsidiaries, agents, licensors, managers, and other
                affiliated companies, and their employees, contractors, agents,
                officers and directors, from and against any and all claims,
                damages, obligations, losses, liabilities, costs or debt, and
                expenses (including but not limited to attorney’s fees) arising
                from:
              </p>
              <br />
              <br />
              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dot */}

                <span>
                  {" "}
                  ⦁ Your use of and access to the Service, including any data or
                  content transmitted or received by you.
                </span>
                <br />
                {/* dot */}
                <span>
                  {" "}
                  ⦁ Your violation of any term of this Agreement, including but
                  not limited to your breach of any of the representations and
                  warranties.
                </span>
                <br />
                {/* dot */}
                <span>
                  {" "}
                  ⦁ Your violation of any third-party right, including but not
                  limited to any right of privacy or Intellectual Property
                  Rights.
                </span>
                <br />
                {/* dot */}
                <span>
                  {" "}
                  ⦁ Your violation of any applicable law, rule or regulation.
                </span>
                <br />
                {/* dot */}
                <span>
                  ⦁ Any content or information that is submitted via your
                  account.
                </span>
                <br />
                {/* dot */}
                <span>
                  {" "}
                  ⦁ Any other party’s access and use of the Services with your
                  unique username, password or other appropriate security code
                </span>
              </p>

              <br />
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                12. TERMINATION/SUSPENSION
              </p>
              <br />
              <br />
              <p>
                Company may, without notice in its sole discretion, and at any
                time, terminate or restrict your use or access to the Website
                (or any part thereof) for any reason, including, without
                limitation, that the company based on its judgement and
                perception believes you have violated or acted inconsistently
                with the letter or spirit of these terms of use.
              </p>

              <br />
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                Terms & Conditions for Online Payments
              </p>
              <br />
              <br />
              <p>
                1. Once a User has accepted these Terms and Conditions, he/ she
                may register and avail the Services.
              </p>
              <br />
              <p>
                2. Server Slow Down/Session Timeout: In case the Website or
                Payment Service Provider’s webpage, that is linked to the
                Website, is experiencing any server related issues like ‘slow
                down’ or ‘failure’ or ‘session timeout’, the User shall, before
                initiating the second payment,, check whether his/her Bank
                Account has been debited or not and accordingly resort to one of
                the following options
              </p>
              <br />
              <br />
              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dot
                                  <span></span>
                                  <br/> */}

                {/* dot */}
                <span>
                  {" "}
                  ⦁ In case the Bank Account appears to be debited, ensure that
                  he/ she does not make the payment twice and immediately
                  thereafter contact the Institute via e-mail or any other mode
                  of contact as provided by the Institute to confirm payment.
                </span>
                <br />

                {/* dot */}
                <span>
                  {" "}
                  ⦁ In case the Bank Account is not debited, the User may
                  initiate a fresh transaction to make payment.
                </span>
                <br />
                {/* dot */}
                <span>
                  {" "}
                  ⦁ However, the User agrees that under no circumstances the
                  Payment Gateway Service Provider shall be held responsible for
                  such fraudulent/duplicate transactions and hence no claims
                  should be raised to Payment Gateway Service Provider No
                  communication received by the Payment Service Provider(s) in
                  this regards shall be entertained by the Payment Service
                  Provider(s).
                </span>
                <br />
              </p>

              <br />
              <br />
              <p>
                3. The Institute and the Payment Service Provider(s) assume no
                liability whatsoever for any monetary or other damage suffered
                by the User on account of:
              </p>
              <br />
              <br />

              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dot
                                  <span></span>
                                  <br/> */}

                {/* dot */}
                <span>
                  {" "}
                  ⦁ The delay, failure, interruption, or corruption of any data
                  or other information transmitted in connection with use of the
                  Payment Gateway or Services in connection thereto; and/ or
                </span>
                <br />

                {/* dot */}
                <span>
                  {" "}
                  ⦁ Any interruption or errors in the operation of the Payment
                  Gateway.
                </span>
                <br />
              </p>

              <br />
              <br />
              <p>
                4. The User agrees, understands and confirms that his/ her
                personal data including without limitation details relating to
                debit card/ credit card transmitted over the Internet may be
                susceptible to misuse, hacking, theft and/ or fraud and that the
                Institute or the Payment Service Provider(s) have no control
                over such matters.{" "}
              </p>
              <br />
              <br />

              <p>
                5. Although all reasonable care has been taken towards guarding
                against unauthorized use of any information transmitted by the
                User, the Institute does not represent or guarantee that the use
                of the Services provided by/ through it will not result in theft
                and/or unauthorized use of data over the Internet.
              </p>
              <br />
              <br />
              <p>
                6. Eumetry, the Institute, the Payment Service Provider(s) and
                its affiliates and associates shall not be liable, at any time,
                for any failure of performance, error, omission, interruption,
                deletion, defect, delay in operation or transmission, computer
                virus, communications line failure, theft or destruction or
                unauthorized access to, alteration of, or use of information
                contained on the Website.
              </p>
              <br />
              <br />
              <p>
                7. The User will be required to login his/ her own User ID and
                Password, given by the Institute in order to register and/ or
                use the Services provided by Institute on Eumetry. By accepting
                these Terms and Conditions the User aggress that his/ her User
                ID and Password are very important pieces of information and it
                shall be the User’s own responsibility to keep them secure and
                confidential. In furtherance hereof, the User agrees to;
              </p>
              <br />
              <br />
              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dot */}
                <span>
                  {" "}
                  ⦁ Choose a new password, whenever required for security
                  reasons.
                </span>
                <br />

                {/* dot */}
                <span>
                  {" "}
                  ⦁ Keep his/ her User ID & Password strictly confidential.
                </span>
                <br />

                {/* dot */}
                <span>
                  {" "}
                  ⦁ Be responsible for any transactions made by User under such
                  User ID and Password.
                </span>
                <br />
              </p>

              <br />
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                Debit/Credit Card, Bank Account Details
              </p>
              <br />
              <br />
              <p>
                {" "}
                1. The User agrees that the debit/credit card details provided
                by him/ her for use of the aforesaid Service(s) must be correct
                and accurate and that the User shall not use a debit/ credit
                card, that is not lawfully owned by him/ her or the use of which
                is not authorized by the lawful owner thereof. The User further
                agrees and undertakes to provide correct and valid debit/credit
                card details.
              </p>
              <br />
              <br />
              <p>
                {" "}
                1. The User agrees that the debit/credit card details provided
                by him/ her for use of the aforesaid Service(s) must be correct
                and accurate and that the User shall not use a debit/ credit
                card, that is not lawfully owned by him/ her or the use of which
                is not authorized by the lawful owner thereof. The User further
                agrees and undertakes to provide correct and valid debit/credit
                card details.
              </p>
              <br />
              <br />
              <p>
                2. The User may pay his/ her fees to the Institute by using a
                debit/credit card or through online banking account. The User
                warrants, agrees and confirms that when he/ she initiates a
                payment transaction and/or issues an online payment instruction
                and provides his/ her card / bank details:
              </p>
              <br />
              <br />
              <p style={{ paddingLeft: "25px", paddingRight: "25px" }}>
                {/* dot */}
                <span>
                  ⦁ The User is fully and lawfully entitled to use such credit /
                  debit card, bank account for such transactions;
                </span>
                <br />

                {/* dot */}
                <span>
                  {" "}
                  ⦁ The User is responsible to ensure that the card/ bank
                  account details provided by him/ her are accurate;
                </span>
                <br />

                {/* dot */}
                <span>
                  ⦁ The User is authorizing debit of the nominated card/ bank
                  account for the payment of fees selected by such User along
                  with the applicable Fees.
                </span>
                <br />

                {/* dot */}
                <span>
                  ⦁ The User is responsible to ensure sufficient credit is
                  available on the nominated card/ bank account at the time of
                  making the payment to permit the payment of the dues payable
                  or the bill(s) selected by the User inclusive of the
                  applicable Fee.
                </span>
                <br />
              </p>

              <br />
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                Payment Gateway Disclaimer
              </p>
              <br />
              <br />
              <p>
                The Service is provided in order to facilitate access to view
                and pay Fees online. Eumetry, the Institute or the Payment
                Service Provider(s) do not make any representation of any kind,
                express or implied, as to the operation of the Payment Gateway
                other than what is specified in the Website for this purpose. By
                accepting/ agreeing to these Terms and Conditions, the User
                expressly agrees that his/ her use of the aforesaid online
                payment Service is entirely at own risk and responsibility of
                the User.
              </p>

              <br />
              <br />
              <br />

              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                Cancellation Policy
              </p>
              <br />
              <br />
              <p>
                Once the User will be registered and paid the Fee through online
                Payment Gateway. He/She will not be able to cancel the
                transaction in any circumstances. No Payment will be refunded to
                the User.
              </p>
              <br />
              <br />
              <br />
              {/* fontSize:"16px" */}
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                Payment Refund Policy for Online Payments
              </p>

              <br />
              <br />
              <div>
                <p style={{ fontWeight: "900", fontSize: "16px" }}>
                  Refund for Charge Back Transaction:{" "}
                </p>
                <span>
                  In the event there is any claim for/ of charge back by the
                  User for any reason whatsoever, such User shall immediately
                  approach the Institute with his/ her claim details and claim
                  refund from the Institute alone. Such refund (if any) shall be
                  effected only by the Institute via payment gateway or any
                  other means as the Institute deems appropriate. No claims for
                  refund/ charge back shall be made by any User to the Eumetry,
                  Payment Service Provider(s) and in the event such claim is
                  made it shall not be entertained.
                </span>
              </div>

              <br />
              <br />
              <br />

              <p style={{ fontWeight: "900", fontSize: "16px" }}>DISCLAIMER</p>

              <br />
              <br />
              <p>
                IN NO EVENT WILL ZOTALABS BE RESPONSIBLE FOR ANY INCIDENTAL,
                CONSEQUENTIAL, DIRECT OR INDIRECT DAMAGES, OR OTHER LOSSES FOR
                ANY USE OF THE WEBSITE, ITS MEMBERS SITES, OR LINKS TO THIRD
                PARTY SITES INCLUDING ANY LOST PROFITS, BUSINESS LOSSES, DATA
                LOSSES, OR ANY PROPERTY LOSSES.
              </p>
              <br />
              <p>
                YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS
                PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. THE SERVICE IS
                PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
                IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
                MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
                NON-INFRINGEMENT OR COURSE OF PERFORMANCE.
              </p>

              <br />
              <p>
                ZOTALABS, ITS SUBSIDIARIES, AFFILIATES, AND ITS LICENSORS DO NOT
                WARRANT THAT A) THE SERVICE WILL FUNCTION UNINTERRUPTED, SECURE
                OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; B) ANY ERRORS
                OR DEFECTS WILL BE CORRECTED; C) THE SERVICE IS FREE OF VIRUSES
                OR OTHER HARMFUL COMPONENTS; OR D) THE RESULTS OF USING THE
                SERVICE WILL MEET YOUR REQUIREMENTS.
              </p>
              <br />
              <p>
                THE CONTENTS OF THE WEBSITE MAY BE SUBJECT TO CHANGE OR UPDATE
                WITHOUT ANY PRIOR NOTICE. WE DO NOT TAKE RESPONSIBILITY OF THE
                ACCURACY OR REDUNDANCY, OR ORIGINALITY OF THE MATERIAL OR ANY
                CONTENTS INCLUDING TEXT, GRAPHICS, CODE, OR OTHER MATERIAL, ON
                THE SITE.
              </p>
              <br />
              <br />
              <br />
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                DISPUTE SETTLEMENT
              </p>
              <br />
              <br />
              <p>
                If any dispute arises between a user/users and Company arising
                out of use of the Website or thereafter, in connection with the
                validity, interpretation, implementation or alleged breach of
                any provision of these Terms of Use, the dispute shall be
                referred to a sole arbitrator who shall be an independent and
                neutral third party identified by the Company. Decision of the
                arbitrator shall be final and binding on both the parties to the
                dispute. The place of arbitration shall be New Delhi, India. The
                Arbitration & Conciliation Act, 1996 as amended, shall govern
                the arbitration proceedings.
              </p>

              <br />
              <p>
                The Company will not be party to any legal proceedings between a
                User (e.g. a subscriber) and a party contacted through the
                Website. In case Company is made a party in any legal
                proceedings, costs will be recovered from the party on whose
                behest the Company is involved in the matter, to which it
                otherwise has no control.
              </p>
              <br />
              <br />
              <br />
              {/* style={{fontWeight:"900",  fontSize:"16px"}} */}
              <p style={{ fontWeight: "900", fontSize: "16px" }}>
                GOVERNING LAW AND JURISDICTION
              </p>

              <br />
              <p style={{ textDecoration: "underline" }}>
                These Terms shall be governed by the laws of Republic of India.
                The exclusive forum for any disputes arising out of or relating
                to these Terms shall be a court of law located in Delhi, India.
              </p>

              <br />
              <br />
              <br />

              <p
                style={{
                  fontWeight: "900",
                  fontSize: "16px",
                  textDecoration: "underline",
                }}
              >
                MISCELLANEOUS
              </p>
              <br />

              <p style={{ textDecoration: "underline" }}>
                If any provision of this Agreement is found to be unenforceable
                or invalid, that provision will be limited or eliminated to the
                minimum extent necessary so that this Agreement will otherwise
                remain in full force and effect and enforceable,
              </p>
              <br />
              <p style={{ textDecoration: "underline" }}>
                No agency, partnership, joint venture, or employment is created
                as a result of this Agreement and you do not have any authority
                of any kind to bind ZOTALABS in any respect whatsoever. There
                are no third party beneficiaries to this Agreement.
              </p>
              <br />
              <p style={{ textDecoration: "underline" }}>
                If you have any questions about this agreement, please contact
                [.].{" "}
              </p>
            </div>
          </div>
          <Button
            variant="orange"
            size="sm"
            id={styles.deleteBatchtbtns}
            style={{ float: "right" }}
            onClick={props.onHide}
            // onClick={deleteParicularBatches}
            // onClick={props.onClickedDelete}
          >
            Close
          </Button>{" "}
        </Modal.Body>
      </Modal>
    </React.Fragment>
  );
};

export default Index;
